const site = {
  // --- Site Metadata ---
  meta: {
    title: "HelloSWX",
    description: "摆专爱国荣校 No.2 & 业余开发者",
    author: "Wenxuan Shen",
    logo: "/logo.svg",
    ogImage: "/og-image.png",
    // HTML lang attribute, affects page language and date formatting
    // Options: "zh-CN", "en", "ja", etc.
    lang: "zh-CN",
  },

  // --- Navigation ---
  // subtitle: decorative label shown below the name (uppercase, small text)
  navigation: [
    { name: "Home", subtitle: "Index", href: "/" },
    { name: "Writing", subtitle: "Blog", href: "/posts" },
    { name: "Projects", subtitle: "Works", href: "/projects" },
    { name: "Friends", subtitle: "Links", href: "/friends" },
    { name: "About", subtitle: "Me", href: "/about" },
  ],

  // --- Social Links ---
  social: [
    {
      name: "GitHub",
      href: "https://github.com/xuanxuan1231",
      icon: "mdi:github",
    },
    { name: "Email", href: "mailto:i@helloswx.top", icon: "mdi:email" },
  ],

  friendCard: {
    name: "Breeze",
    description: "A minimal Astro theme for personal websites",
    link: "https://your-domain.com",
    avatar: "https://your-domain.com/logo.svg",
  },

  // --- Homepage Hero ---
  hero: {
    greeting: "👋 Hi, I'm HelloSWX",
    // Supports HTML. Use <span class="font-medium text-foreground underline decoration-primary/30"> to highlight keywords
    description: "每天在海淀黄庄环形通勤的高中牲",
    cards: [
      { icon: "mdi:explore", label: "Status", value: "Coding, Meowing" },
      { icon: "mdi:location", label: "Location", value: "The Universe" },
    ],
  },

  // --- Footer ---
  footer: {
    copyright: "© 2026 HelloSWX",
    builtWith: "Built with Astro",
  },

  // --- Comments (giscus, powered by GitHub Discussions) ---
  // Fill in the values below from https://giscus.app:
  //   1. Make the repository public, enable Discussions, and install the giscus app
  //   2. Configure giscus.app and copy the generated `data-*` attributes
  //   3. Paste them into `giscus` below
  // While required fields are empty, the comment section stays hidden.
  comments: {
    enabled: true,
    provider: "giscus" as const,
    giscus: {
      // --- Required (from the <script> tag generated by giscus.app) ---
      repo: "xuanxuan1231/blog", // data-repo: "owner/repo"
      repoId: "R_kgDOU8h6Mw", // data-repo-id
      category: "Announcements", // data-category: discussion category name
      categoryId: "DIC_kwDOU8h6M84DHRBs", // data-category-id

      // --- Optional ---
      // data-mapping: "pathname" | "url" | "title" | "og:title" | "specific" | "number"
      mapping: "pathname" as const,
      term: "", // data-term: only used when mapping is "specific"
      strict: false, // data-strict: strict title matching
      reactionsEnabled: true, // data-reactions-enabled
      // data-emit-metadata: keep true to show comment counts on post pages
      emitMetadata: true,
      inputPosition: "bottom" as const, // data-input-position: "top" | "bottom"
      lang: "zh-CN", // data-lang
      // Theme per site mode. The two stylesheets in `public/` mirror the site
      // palette from src/styles/theme.css and follow the site's light/dark
      // toggle. giscus loads them cross-origin from its iframe, hence the CORS
      // headers in `public/_headers` (Netlify). Built-in giscus theme names
      // (light, dark, preferred_color_scheme, ...) or external `https://` theme
      // URLs also work here.
      lightTheme: "/giscus-theme-light.css",
      darkTheme: "/giscus-theme-dark.css",
    },
  },

  // --- Feature Toggles ---
  features: {
    search: true,
    rss: true,
    // Auto-mark posts as "new" if published within this many days (0 to disable)
    newPostDays: 7,
  },

  // --- Tools Page Data ---
  // Each item can use either `icon` (Iconify name) or `logo` (public path or { light, dark } paths)
  tools: [
    {
      name: "development",
      items: [
        {
          name: "VS Code",
          link: "https://code.visualstudio.com",
          icon: "mdi:microsoft-visual-studio-code",
        },
        {
          name: "WebStorm",
          link: "https://www.jetbrains.com/webstorm",
          icon: "mdi:code-braces",
        },
        { name: "Terminal", icon: "mdi:terminal" },
        { name: "Git", link: "https://git-scm.com", icon: "mdi:git" },
        { name: "Docker", link: "https://www.docker.com", icon: "mdi:docker" },
        { name: "Postman", link: "https://www.postman.com", icon: "mdi:api" },
      ],
    },
    {
      name: "design",
      items: [
        {
          name: "Figma",
          link: "https://www.figma.com",
          icon: "mdi:vector-polygon",
        },
        {
          name: "Sketch",
          link: "https://www.sketch.com",
          icon: "mdi:vector-square",
        },
        {
          name: "Adobe XD",
          link: "https://www.adobe.com/products/xd.html",
          icon: "mdi:pencil-ruler",
        },
        {
          name: "Photoshop",
          link: "https://www.adobe.com/products/photoshop.html",
          icon: "mdi:image-edit",
        },
      ],
    },
    {
      name: "productivity",
      items: [
        { name: "Notion", link: "https://www.notion.so", icon: "mdi:notebook" },
        {
          name: "Obsidian",
          link: "https://obsidian.md",
          icon: "mdi:diamond-stone",
        },
        {
          name: "Raycast",
          link: "https://www.raycast.com",
          icon: "mdi:lightning-bolt",
        },
        { name: "Arc Browser", link: "https://arc.net", icon: "mdi:web" },
      ],
    },
  ],

  // --- UI Labels ---
  // Customize these values to change the text displayed on pages
  labels: {
    postsTitle: "Writing",
    postsDescription: "小笔记，小想法",
    projectsTitle: "Projects",
    projectsDescription: "有些是自己的，有些是和别人一起的",
    friendsTitle: "Friends",
    friendsDescription: "都哥们",
    toolsTitle: "Stack",
    aboutTitle: "About",
    aboutDescription: "我就是我",
    backToPosts: "Back to posts",
    goHome: "Go Home",
    notFoundTitle: "你大抵是走错路了",
    notFoundDescription: "这里已经什么都没有了喵",
    endOfPost: "End of Post",
    tableOfContents: "内容",
    searchPlaceholder: "搜索一切...",
    searchNavigate: "Goooo!",
  },

  ogImage: "/og-image.png",
} as const;

export default site;
